name = "portfolio-sveltekit"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-01-24"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare/assets"
binding = "ASSETS"

